/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FMD_RPC_API_H_RPCGEN
#define	_FMD_RPC_API_H_RPCGEN

#include <rpc/rpc.h>
#ifndef _KERNEL
#include <synch.h>
#include <thread.h>
#endif /* !_KERNEL */

#ifdef __cplusplus
extern "C" {
#endif

extern void fmd_api_1(struct svc_req *, SVCXPRT *);
#undef	RW_READ_HELD
#undef	RW_WRITE_HELD
#undef	RW_LOCK_HELD
#undef	MUTEX_HELD

#define	FMD_API	100170
#define	FMD_API_VERSION_1	1

#if defined(__STDC__) || defined(__cplusplus)
#define	FMD_HDL_CREATE	1
extern  enum clnt_stat fmd_hdl_create_1(int , void *, CLIENT *);
extern  bool_t fmd_hdl_create_1_svc(int , void *, struct svc_req *);
extern int fmd_api_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	FMD_HDL_CREATE	1
extern  enum clnt_stat fmd_hdl_create_1();
extern  bool_t fmd_hdl_create_1_svc();
extern int fmd_api_1_freeresult();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FMD_RPC_API_H_RPCGEN */
