/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fmd_rpc_api.h"

extern void fmd_api_1(struct svc_req *, SVCXPRT *);
#undef RW_READ_HELD
#undef RW_WRITE_HELD
#undef RW_LOCK_HELD
#undef MUTEX_HELD
