/*
 * Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */

#include <libtopo.h>
#include "topo_mod.h"
#include "topo_subr.h"

topo_name_trans_t topo_sensor_type_table[] = {
	{ TOPO_SENSOR_TYPE_RESERVED, "RESERVED" },
	{ TOPO_SENSOR_TYPE_TEMP, "TEMP" },
	{ TOPO_SENSOR_TYPE_VOLTAGE, "VOLTAGE" },
	{ TOPO_SENSOR_TYPE_CURRENT, "CURRENT" },
	{ TOPO_SENSOR_TYPE_FAN, "FAN" },
	{ TOPO_SENSOR_TYPE_PHYSICAL, "PHYSICAL" },
	{ TOPO_SENSOR_TYPE_PLATFORM, "PLATFORM" },
	{ TOPO_SENSOR_TYPE_PROCESSOR, "PROCESSOR" },
	{ TOPO_SENSOR_TYPE_POWER_SUPPLY, "POWER_SUPPLY" },
	{ TOPO_SENSOR_TYPE_POWER_UNIT, "POWER_UNIT" },
	{ TOPO_SENSOR_TYPE_COOLING, "COOLING" },
	{ TOPO_SENSOR_TYPE_OTHER, "OTHER" },
	{ TOPO_SENSOR_TYPE_MEMORY, "MEMORY" },
	{ TOPO_SENSOR_TYPE_BAY, "BAY" },
	{ TOPO_SENSOR_TYPE_POST_RESIZE, "POST_RESIZE" },
	{ TOPO_SENSOR_TYPE_FIRMWARE, "FIRMWARE" },
	{ TOPO_SENSOR_TYPE_EVENT_LOG, "EVENT_LOG" },
	{ TOPO_SENSOR_TYPE_WATCHDOG1, "WATCHDOG1" },
	{ TOPO_SENSOR_TYPE_SYSTEM, "SYSTEM" },
	{ TOPO_SENSOR_TYPE_CRITICAL, "CRITICAL" },
	{ TOPO_SENSOR_TYPE_BUTTON, "BUTTON" },
	{ TOPO_SENSOR_TYPE_MODULE, "MODULE" },
	{ TOPO_SENSOR_TYPE_MICROCONTROLLER, "MICROCONTROLLER" },
	{ TOPO_SENSOR_TYPE_CARD, "CARD" },
	{ TOPO_SENSOR_TYPE_CHASSIS, "CHASSIS" },
	{ TOPO_SENSOR_TYPE_CHIPSET, "CHIPSET" },
	{ TOPO_SENSOR_TYPE_FRU, "FRU" },
	{ TOPO_SENSOR_TYPE_CABLE, "CABLE" },
	{ TOPO_SENSOR_TYPE_TERMINATOR, "TERMINATOR" },
	{ TOPO_SENSOR_TYPE_BOOT_STATE, "BOOT_STATE" },
	{ TOPO_SENSOR_TYPE_BOOT_ERROR, "BOOT_ERROR" },
	{ TOPO_SENSOR_TYPE_BOOT_OS, "BOOT_OS" },
	{ TOPO_SENSOR_TYPE_OS_SHUTDOWN, "OS_SHUTDOWN" },
	{ TOPO_SENSOR_TYPE_SLOT, "SLOT" },
	{ TOPO_SENSOR_TYPE_ACPI, "ACPI" },
	{ TOPO_SENSOR_TYPE_WATCHDOG2, "WATCHDOG2" },
	{ TOPO_SENSOR_TYPE_ALERT, "ALERT" },
	{ TOPO_SENSOR_TYPE_PRESENCE, "PRESENCE" },
	{ TOPO_SENSOR_TYPE_ASIC, "ASIC" },
	{ TOPO_SENSOR_TYPE_LAN, "LAN" },
	{ TOPO_SENSOR_TYPE_HEALTH, "HEALTH" },
	{ TOPO_SENSOR_TYPE_BATTERY, "BATTERY" },
	{ TOPO_SENSOR_TYPE_AUDIT, "AUDIT" },
	{ TOPO_SENSOR_TYPE_VERSION, "VERSION" },
	{ TOPO_SENSOR_TYPE_FRU_STATE, "FRU_STATE" },
	{ TOPO_SENSOR_TYPE_THRESHOLD_STATE, "THRESHOLD_STATE" },
	{ TOPO_SENSOR_TYPE_GENERIC_USAGE, "GENERIC_USAGE" },
	{ TOPO_SENSOR_TYPE_GENERIC_STATE, "GENERIC_STATE" },
	{ TOPO_SENSOR_TYPE_GENERIC_PREDFAIL, "GENERIC_PREDFAIL" },
	{ TOPO_SENSOR_TYPE_GENERIC_LIMIT, "GENERIC_LIMIT" },
	{ TOPO_SENSOR_TYPE_GENERIC_PERFORMANCE, "GENERIC_PERFORMANCE" },
	{ TOPO_SENSOR_TYPE_SEVERITY, "SEVERITY" },
	{ TOPO_SENSOR_TYPE_GENERIC_PRESENCE, "GENERIC_PRESENCE" },
	{ TOPO_SENSOR_TYPE_GENERIC_AVAILABILITY, "GENERIC_AVAILABILITY" },
	{ TOPO_SENSOR_TYPE_GENERIC_STATUS, "GENERIC_STATUS" },
	{ TOPO_SENSOR_TYPE_GENERIC_REDUNDANCY, "GENERIC_REDUNDANCY" },
	{ TOPO_SENSOR_TYPE_GENERIC_ACPI, "GENERIC_ACPI" },
	{ TOPO_SENSOR_TYPE_GENERIC_FAILURE, "GENERIC_FAILURE" },
	{ TOPO_SENSOR_TYPE_GENERIC_OK, "GENERIC_OK" },
	{ 0, NULL }
};

topo_name_trans_t topo_units_type_table[] = {
	{ TOPO_SENSOR_UNITS_UNSPECIFIED, "UNSPECIFIED" },
	{ TOPO_SENSOR_UNITS_DEGREES_C, "DEGREES_C" },
	{ TOPO_SENSOR_UNITS_DEGREES_F, "DEGREES_F" },
	{ TOPO_SENSOR_UNITS_DEGREES_K, "DEGREES_K" },
	{ TOPO_SENSOR_UNITS_VOLTS, "VOLTS" },
	{ TOPO_SENSOR_UNITS_AMPS, "AMPS" },
	{ TOPO_SENSOR_UNITS_WATTS, "WATTS" },
	{ TOPO_SENSOR_UNITS_JOULES, "JOULES" },
	{ TOPO_SENSOR_UNITS_COULOMBS, "COULOMBS" },
	{ TOPO_SENSOR_UNITS_VA, "VA" },
	{ TOPO_SENSOR_UNITS_NITS, "NITS" },
	{ TOPO_SENSOR_UNITS_LUMEN, "LUMEN" },
	{ TOPO_SENSOR_UNITS_LUX, "LUX" },
	{ TOPO_SENSOR_UNITS_CANDELA, "CANDELA" },
	{ TOPO_SENSOR_UNITS_KPA, "KPA" },
	{ TOPO_SENSOR_UNITS_PSI, "PSI" },
	{ TOPO_SENSOR_UNITS_NEWTON, "NEWTON" },
	{ TOPO_SENSOR_UNITS_CFM, "CFM" },
	{ TOPO_SENSOR_UNITS_RPM, "RPM" },
	{ TOPO_SENSOR_UNITS_HZ, "HZ" },
	{ TOPO_SENSOR_UNITS_MICROSEC, "MICROSEC" },
	{ TOPO_SENSOR_UNITS_MILLISEC, "MILLISEC" },
	{ TOPO_SENSOR_UNITS_SECS, "SECS" },
	{ TOPO_SENSOR_UNITS_MIN, "MIN" },
	{ TOPO_SENSOR_UNITS_HOUR, "HOUR" },
	{ TOPO_SENSOR_UNITS_DAY, "DAY" },
	{ TOPO_SENSOR_UNITS_WEEK, "WEEK" },
	{ TOPO_SENSOR_UNITS_MIL, "MIL" },
	{ TOPO_SENSOR_UNITS_INCHES, "INCHES" },
	{ TOPO_SENSOR_UNITS_FEET, "FEET" },
	{ TOPO_SENSOR_UNITS_CUB_INCH, "CUB_INCH" },
	{ TOPO_SENSOR_UNITS_CUB_FEET, "CUB_FEET" },
	{ TOPO_SENSOR_UNITS_MM, "MM" },
	{ TOPO_SENSOR_UNITS_CM, "CM" },
	{ TOPO_SENSOR_UNITS_METERS, "METERS" },
	{ TOPO_SENSOR_UNITS_CUB_CM, "CUB_CM" },
	{ TOPO_SENSOR_UNITS_CUB_METER, "CUB_METER" },
	{ TOPO_SENSOR_UNITS_LITERS, "LITERS" },
	{ TOPO_SENSOR_UNITS_FLUID_OUNCE, "FLUID_OUNCE" },
	{ TOPO_SENSOR_UNITS_RADIANS, "RADIANS" },
	{ TOPO_SENSOR_UNITS_STERADIANS, "STERADIANS" },
	{ TOPO_SENSOR_UNITS_REVOLUTIONS, "REVOLUTIONS" },
	{ TOPO_SENSOR_UNITS_CYCLES, "CYCLES" },
	{ TOPO_SENSOR_UNITS_GRAVITIES, "GRAVITIES" },
	{ TOPO_SENSOR_UNITS_OUNCE, "OUNCE" },
	{ TOPO_SENSOR_UNITS_POUND, "POUND" },
	{ TOPO_SENSOR_UNITS_FOOT_POUND, "FOOT_POUND" },
	{ TOPO_SENSOR_UNITS_OZ_INCH, "OZ_INCH" },
	{ TOPO_SENSOR_UNITS_GAUSS, "GAUSS" },
	{ TOPO_SENSOR_UNITS_GILBERTS, "GILBERTS" },
	{ TOPO_SENSOR_UNITS_HENRY, "HENRY" },
	{ TOPO_SENSOR_UNITS_MILHENRY, "MILHENRY" },
	{ TOPO_SENSOR_UNITS_FARAD, "FARAD" },
	{ TOPO_SENSOR_UNITS_MICROFARAD, "MICROFARAD" },
	{ TOPO_SENSOR_UNITS_OHMS, "OHMS" },
	{ TOPO_SENSOR_UNITS_SIEMENS, "SIEMENS" },
	{ TOPO_SENSOR_UNITS_MOLE, "MOLE" },
	{ TOPO_SENSOR_UNITS_BECQUEREL, "BECQUEREL" },
	{ TOPO_SENSOR_UNITS_PPM, "PPM" },
	{ TOPO_SENSOR_UNITS_RESERVED1, "RESERVED1" },
	{ TOPO_SENSOR_UNITS_DECIBELS, "DECIBELS" },
	{ TOPO_SENSOR_UNITS_DBA, "DBA" },
	{ TOPO_SENSOR_UNITS_DBC, "DBC" },
	{ TOPO_SENSOR_UNITS_GRAY, "GRAY" },
	{ TOPO_SENSOR_UNITS_SIEVERT, "SIEVERT" },
	{ TOPO_SENSOR_UNITS_COLOR_TEMP_K, "COLOR_TEMP_K" },
	{ TOPO_SENSOR_UNITS_BIT, "BIT" },
	{ TOPO_SENSOR_UNITS_KILOBIT, "KILOBIT" },
	{ TOPO_SENSOR_UNITS_MEGABIT, "MEGABIT" },
	{ TOPO_SENSOR_UNITS_GIGABIT, "GIGABIT" },
	{ TOPO_SENSOR_UNITS_BYTE, "BYTE" },
	{ TOPO_SENSOR_UNITS_KILOBYTE, "KILOBYTE" },
	{ TOPO_SENSOR_UNITS_MEGABYTE, "MEGABYTE" },
	{ TOPO_SENSOR_UNITS_GIGABYTE, "GIGABYTE" },
	{ TOPO_SENSOR_UNITS_WORD, "WORD" },
	{ TOPO_SENSOR_UNITS_DWORD, "DWORD" },
	{ TOPO_SENSOR_UNITS_QWORD, "QWORD" },
	{ TOPO_SENSOR_UNITS_MEMLINE, "MEMLINE" },
	{ TOPO_SENSOR_UNITS_HIT, "HIT" },
	{ TOPO_SENSOR_UNITS_MISS, "MISS" },
	{ TOPO_SENSOR_UNITS_RETRY, "RETRY" },
	{ TOPO_SENSOR_UNITS_RESET, "RESET" },
	{ TOPO_SENSOR_UNITS_OVERFLOW, "OVERFLOW" },
	{ TOPO_SENSOR_UNITS_UNDERRUN, "UNDERRUN" },
	{ TOPO_SENSOR_UNITS_COLLISION, "COLLISION" },
	{ TOPO_SENSOR_UNITS_PACKETS, "PACKETS" },
	{ TOPO_SENSOR_UNITS_MESSAGES, "MESSAGES" },
	{ TOPO_SENSOR_UNITS_CHARACTERS, "CHARACTERS" },
	{ TOPO_SENSOR_UNITS_ERROR, "ERROR" },
	{ TOPO_SENSOR_UNITS_CE, "CE" },
	{ TOPO_SENSOR_UNITS_UE, "UE" },
	{ TOPO_SENSOR_UNITS_FATAL_ERROR, "FATAL_ERROR" },
	{ TOPO_SENSOR_UNITS_GRAMS, "GRAMS" },
	{ 0, NULL }
};

topo_name_trans_t topo_led_type_table[] = {
	{ TOPO_LED_TYPE_SERVICE, "SERVICE" },
	{ TOPO_LED_TYPE_LOCATE, "LOCATE" },
	{ TOPO_LED_TYPE_OK2RM, "OK2RM" },
	{ TOPO_LED_TYPE_PRESENT, "PRESENT" },
	{ 0, NULL }
};

topo_name_trans_t topo_led_states_table[] = {
	{ TOPO_LED_STATE_OFF, "OFF" },
	{ TOPO_LED_STATE_ON, "ON" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_physical_table[] = {
	{ TOPO_SENSOR_STATE_PHYSICAL_GENERAL, "GENERAL" },
	{ TOPO_SENSOR_STATE_PHYSICAL_BAY, "BAY" },
	{ TOPO_SENSOR_STATE_PHYSICAL_CARD, "CARD" },
	{ TOPO_SENSOR_STATE_PHYSICAL_PROCESSOR, "PROCESSOR" },
	{ TOPO_SENSOR_STATE_PHYSICAL_LAN, "LAN" },
	{ TOPO_SENSOR_STATE_PHYSICAL_DOCK, "DOCK" },
	{ TOPO_SENSOR_STATE_PHYSICAL_FAN, "FAN" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_platform_table[] = {
	{ TOPO_SENSOR_STATE_PLATFORM_SECURE, "SECURE" },
	{ TOPO_SENSOR_STATE_PLATFORM_USER_PASS, "USER_PASS" },
	{ TOPO_SENSOR_STATE_PLATFORM_SETUP_PASS, "SETUP_PASS" },
	{ TOPO_SENSOR_STATE_PLATFORM_NETWORK_PASS, "NETWORK_PASS" },
	{ TOPO_SENSOR_STATE_PLATFORM_OTHER_PASS, "OTHER_PASS" },
	{ TOPO_SENSOR_STATE_PLATFORM_OUT_OF_BAND, "OUT_OF_BAND" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_processor_table[] = {
	{ TOPO_SENSOR_STATE_PROCESSOR_IERR, "IERR" },
	{ TOPO_SENSOR_STATE_PROCESSOR_THERMAL, "THERMAL" },
	{ TOPO_SENSOR_STATE_PROCESSOR_FRB1, "FRB1" },
	{ TOPO_SENSOR_STATE_PROCESSOR_FRB2, "FRB2" },
	{ TOPO_SENSOR_STATE_PROCESSOR_FRB3, "FRB3" },
	{ TOPO_SENSOR_STATE_PROCESSOR_CONFIG, "CONFIG" },
	{ TOPO_SENSOR_STATE_PROCESSOR_SMBIOS, "SMBIOS" },
	{ TOPO_SENSOR_STATE_PROCESSOR_PRESENT, "PRESENT" },
	{ TOPO_SENSOR_STATE_PROCESSOR_DISABLED, "DISABLED" },
	{ TOPO_SENSOR_STATE_PROCESSOR_TERMINATOR, "TERMINATOR" },
	{ TOPO_SENSOR_STATE_PROCESSOR_THROTTLED, "THROTTLED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_power_supply_table[] = {
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_PRESENT, "PRESENT" },
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_FAILURE, "FAILURE" },
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_PREDFAIL, "PREDFAIL" },
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_INPUT_LOST, "INPUT_LOST" },
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_INPUT_RANGE, "INPUT_RANGE" },
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_INPUT_RANGE_PRES, "INPUT_RANGE_PRES" },
	{ TOPO_SENSOR_STATE_POWER_SUPPLY_CONFIG_ERR, "CONFIG_ERR" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_power_unit_table[] = {
	{ TOPO_SENSOR_STATE_POWER_UNIT_OFF, "OFF" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_CYCLE, "CYCLE" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_240_DOWN, "240_DOWN" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_INTERLOCK_DOWN, "INTERLOCK_DOWN" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_AC_LOST, "AC_LOST" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_SOFT_FAILURE, "SOFT_FAILURE" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_FAIL, "FAIL" },
	{ TOPO_SENSOR_STATE_POWER_UNIT_PREDFAIL, "PREDFAIL" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_memory_table[] = {
	{ TOPO_SENSOR_STATE_MEMORY_CE, "CE" },
	{ TOPO_SENSOR_STATE_MEMORY_UE, "UE" },
	{ TOPO_SENSOR_STATE_MEMORY_PARITY, "PARITY" },
	{ TOPO_SENSOR_STATE_MEMORY_SCRUB_FAIL, "SCRUB_FAIL" },
	{ TOPO_SENSOR_STATE_MEMORY_DISABLED, "DISABLED" },
	{ TOPO_SENSOR_STATE_MEMORY_CE_LOG_LIMIT, "CE_LOG_LIMIT" },
	{ TOPO_SENSOR_STATE_MEMORY_PRESENT, "PRESENT" },
	{ TOPO_SENSOR_STATE_MEMORY_CONFIG_ERR, "CONFIG_ERR" },
	{ TOPO_SENSOR_STATE_MEMORY_SPARE, "SPARE" },
	{ TOPO_SENSOR_STATE_MEMORY_THROTTLED, "THROTTLED" },
	{ TOPO_SENSOR_STATE_MEMORY_OVERTEMP, "OVERTEMP" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_bay_table[] = {
	{ TOPO_SENSOR_STATE_BAY_PRESENT, "PRESENT" },
	{ TOPO_SENSOR_STATE_BAY_FAULT, "FAULT" },
	{ TOPO_SENSOR_STATE_BAY_PREDFAIL, "PREDFAIL" },
	{ TOPO_SENSOR_STATE_BAY_SPARE, "SPARE" },
	{ TOPO_SENSOR_STATE_BAY_CHECK, "CHECK" },
	{ TOPO_SENSOR_STATE_BAY_CRITICAL, "CRITICAL" },
	{ TOPO_SENSOR_STATE_BAY_FAILED, "FAILED" },
	{ TOPO_SENSOR_STATE_BAY_REBUILDING, "REBUILDING" },
	{ TOPO_SENSOR_STATE_BAY_ABORTED, "ABORTED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_firmware_table[] = {
	{ TOPO_SENSOR_STATE_FIRMWARE_ERROR, "ERROR" },
	{ TOPO_SENSOR_STATE_FIRMWARE_HANG, "HANG" },
	{ TOPO_SENSOR_STATE_FIRMWARE_PROGRESS, "PROGRESS" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_event_log_table[] = {
	{ TOPO_SENSOR_STATE_EVENT_LOG_CE, "CE" },
	{ TOPO_SENSOR_STATE_EVENT_LOG_TYPE, "TYPE" },
	{ TOPO_SENSOR_STATE_EVENT_LOG_RESET, "RESET" },
	{ TOPO_SENSOR_STATE_EVENT_LOG_ALL, "ALL" },
	{ TOPO_SENSOR_STATE_EVENT_LOG_FULL, "FULL" },
	{ TOPO_SENSOR_STATE_EVENT_LOG_ALMOST_FULL, "ALMOST_FULL" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_watchdog1_table[] = {
	{ TOPO_SENSOR_STATE_WATCHDOG_BIOS_RESET, "BIOS_RESET" },
	{ TOPO_SENSOR_STATE_WATCHDOG_OS_RESET, "OS_RESET" },
	{ TOPO_SENSOR_STATE_WATCHDOG_OS_SHUTDOWN, "OS_SHUTDOWN" },
	{ TOPO_SENSOR_STATE_WATCHDOG_OS_PWR_DOWN, "OS_PWR_DOWN" },
	{ TOPO_SENSOR_STATE_WATCHDOG_OS_PWR_CYCLE, "OS_PWR_CYCLE" },
	{ TOPO_SENSOR_STATE_WATCHDOG_OS_NMI_DIAG, "OS_NMI_DIAG" },
	{ TOPO_SENSOR_STATE_WATCHDOG_EXPIRED, "EXPIRED" },
	{ TOPO_SENSOR_STATE_WATCHDOG_PRE_TIMEOUT_INT, "PRE_TIMEOUT_INT" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_system_table[] = {
	{ TOPO_SENSOR_STATE_SYSTEM_RECONF, "RECONF" },
	{ TOPO_SENSOR_STATE_SYSTEM_BOOT, "BOOT" },
	{ TOPO_SENSOR_STATE_SYSTEM_UNKNOWN_HW_FAILURE, "UNKNOWN_HW_FAILURE" },
	{ TOPO_SENSOR_STATE_SYSTEM_AUX_LOG_UPDATED, "AUX_LOG_UPDATED" },
	{ TOPO_SENSOR_STATE_SYSTEM_PEF_ACTION, "PEF_ACTION" },
	{ TOPO_SENSOR_STATE_SYSTEM_TIMETAMP_CLOCKSYNC, "TIMETAMP_CLOCKSYNC" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_critical_table[] = {
	{ TOPO_SENSOR_STATE_CRITICAL_EXT_NMI, "EXT_NMI" },
	{ TOPO_SENSOR_STATE_CRITICAL_BUS_TIMEOUT, "BUS_TIMEOUT" },
	{ TOPO_SENSOR_STATE_CRITICAL_IO_NMI, "IO_NMI" },
	{ TOPO_SENSOR_STATE_CRITICAL_SW_NMI, "SW_NMI" },
	{ TOPO_SENSOR_STATE_CRITICAL_PCI_PERR, "PCI_PERR" },
	{ TOPO_SENSOR_STATE_CRITICAL_PCI_SERR, "PCI_SERR" },
	{ TOPO_SENSOR_STATE_CRITICAL_EISA_FAILSAFE, "EISA_FAILSAFE" },
	{ TOPO_SENSOR_STATE_CRITICAL_BUS_CE, "BUS_CE" },
	{ TOPO_SENSOR_STATE_CRITICAL_BUS_UE, "BUS_UE" },
	{ TOPO_SENSOR_STATE_CRITICAL_FATAL_NMI, "FATAL_NMI" },
	{ TOPO_SENSOR_STATE_CRITICAL_BUS_FATAL_ERR, "BUS_FATAL_ERR" },
	{ TOPO_SENSOR_STATE_CRITICAL_BUS_DEGRADED, "BUS_DEGRADED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_button_table[] = {
	{ TOPO_SENSOR_STATE_BUTTON_PWR, "PWR" },
	{ TOPO_SENSOR_STATE_BUTTON_SLEEP, "SLEEP" },
	{ TOPO_SENSOR_STATE_BUTTON_RESET, "RESET" },
	{ TOPO_SENSOR_STATE_BUTTON_FRU_LATCH, "FRU_LATCH" },
	{ TOPO_SENSOR_STATE_BUTTON_FRU_SERVICE, "FRU_SERVICE" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_cable_table[] = {
	{ TOPO_SENSOR_STATE_CABLE_CONNECTED, "CONNECTED" },
	{ TOPO_SENSOR_STATE_CABLE_CONFIG_ERR, "CONFIG_ERR" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_boot_state_table[] = {
	{ TOPO_SENSOR_STATE_BOOT_STATE_BIOS_PWR_UP, "BIOS_PWR_UP" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_BIOS_HARD_RESET, "BIOS_HARD_RESET" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_BIOS_WARM_RESET, "BIOS_WARM_RESET" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_PXE_BOOT, "PXE_BOOT" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_DIAG_BOOT, "DIAG_BOOT" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_OS_HARD_RESET, "OS_HARD_RESET" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_OS_WARM_RESET, "OS_WARM_RESET" },
	{ TOPO_SENSOR_STATE_BOOT_STATE_SYS_RESTART, "SYS_RESTART" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_boot_error_table[] = {
	{ TOPO_SENSOR_STATE_BOOT_ERROR_NOMEDIA, "NOMEDIA" },
	{ TOPO_SENSOR_STATE_BOOT_ERROR_NON_BOOTABLE_DISK, "NON_BOOTABLE_DISK" },
	{ TOPO_SENSOR_STATE_BOOT_ERROR_NO_PXE_SERVER, "NO_PXE_SERVER" },
	{ TOPO_SENSOR_STATE_BOOT_ERROR_INV_BOOT_SECT, "INV_BOOT_SECT" },
	{ TOPO_SENSOR_STATE_BOOT_ERROR_USR_SELECT_TIMEOUT, "USR_SELECT_TIMEOUT" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_boot_os_table[] = {
	{ TOPO_SENSOR_STATE_BOOT_OS_A_DRV_BOOT_COMPLETE, "A_DRV_BOOT_COMPLETE" },
	{ TOPO_SENSOR_STATE_BOOT_OS_C_DRV_BOOT_COMPLETE, "C_DRV_BOOT_COMPLETE" },
	{ TOPO_SENSOR_STATE_BOOT_OS_PXE_BOOT_COMPLETE, "PXE_BOOT_COMPLETE" },
	{ TOPO_SENSOR_STATE_BOOT_OS_DIAG_BOOT_COMPLETE, "DIAG_BOOT_COMPLETE" },
	{ TOPO_SENSOR_STATE_BOOT_OS_CDROM_BOOT_COMPLETE, "CDROM_BOOT_COMPLETE" },
	{ TOPO_SENSOR_STATE_BOOT_OS_ROM_BOOT_COMPLETE, "ROM_BOOT_COMPLETE" },
	{ TOPO_SENSOR_STATE_BOOT_OS_UNSPEC_BOOT_COMPLETE, "UNSPEC_BOOT_COMPLETE" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_os_table[] = {
	{ TOPO_SENSOR_STATE_OS_SHUTDOWN_LOADING, "SHUTDOWN_LOADING" },
	{ TOPO_SENSOR_STATE_OS_SHUTDOWN_CRASH, "SHUTDOWN_CRASH" },
	{ TOPO_SENSOR_STATE_OS_STOP_GRACEFUL, "STOP_GRACEFUL" },
	{ TOPO_SENSOR_STATE_OS_SHUTDOWN_GRACEFUL, "SHUTDOWN_GRACEFUL" },
	{ TOPO_SENSOR_STATE_OS_SHUTDOWN_PEF, "SHUTDOWN_PEF" },
	{ TOPO_SENSOR_STATE_OS_SHUTDOWN_BMC, "SHUTDOWN_BMC" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_slot_table[] = {
	{ TOPO_SENSOR_STATE_SLOT_FAULT_ASSERTED, "FAULT_ASSERTED" },
	{ TOPO_SENSOR_STATE_SLOT_IDENTIFY_ASSERTED, "IDENTIFY_ASSERTED" },
	{ TOPO_SENSOR_STATE_SLOT_CONNECTED, "CONNECTED" },
	{ TOPO_SENSOR_STATE_SLOT_INSTALL_READY, "INSTALL_READY" },
	{ TOPO_SENSOR_STATE_SLOT_REMOVE_READY, "REMOVE_READY" },
	{ TOPO_SENSOR_STATE_SLOT_PWR_OFF, "PWR_OFF" },
	{ TOPO_SENSOR_STATE_SLOT_REMOVED, "REMOVED" },
	{ TOPO_SENSOR_STATE_SLOT_INTERLOCK_ASSERTED, "INTERLOCK_ASSERTED" },
	{ TOPO_SENSOR_STATE_SLOT_DISABLED, "DISABLED" },
	{ TOPO_SENSOR_STATE_SLOT_SPARE_DEVICE, "SPARE_DEVICE" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_acpi_table[] = {
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S0_G0, "PSTATE_S0_G0" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S1, "PSTATE_S1" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S2, "PSTATE_S2" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S3, "PSTATE_S3" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S4, "PSTATE_S4" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S5_G2_SOFT_OFF, "PSTATE_S5_G2_SOFT_OFF" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S4_S5_SOFT_OFF, "PSTATE_S4_S5_SOFT_OFF" },
	{ TOPO_SENSOR_STATE_ACPI_PSATTE_G3_MECH_OFF, "PSATTE_G3_MECH_OFF" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S1_S2_S3_SLEEP, "PSTATE_S1_S2_S3_SLEEP" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_G1_SLEEP, "PSTATE_G1_SLEEP" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_S5_OVERRIDE, "PSTATE_S5_OVERRIDE" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_LEGACY_ON, "PSTATE_LEGACY_ON" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_LEGACY_OFF, "PSTATE_LEGACY_OFF" },
	{ TOPO_SENSOR_STATE_ACPI_PSTATE_UNKNOWN, "PSTATE_UNKNOWN" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_watchdog2_table[] = {
	{ TOPO_SENSOR_STATE_WATCHDOG2_EXPIRED, "EXPIRED" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_HARD_RESET, "HARD_RESET" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_PWR_DOWN, "PWR_DOWN" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_PWR_CYCLE, "PWR_CYCLE" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_RESERVED1, "RESERVED1" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_RESERVED2, "RESERVED2" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_RESERVED3, "RESERVED3" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_RESERVED4, "RESERVED4" },
	{ TOPO_SENSOR_STATE_WATCHDOG2_TIMEOUT_INT, "TIMEOUT_INT" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_alert_table[] = {
	{ TOPO_SENSOR_STATE_ALERT_PLAT_PAGE, "PLAT_PAGE" },
	{ TOPO_SENSOR_STATE_ALERT_PLAT_LAN_ALERT, "PLAT_LAN_ALERT" },
	{ TOPO_SENSOR_STATE_ALERT_PLAT_EVT_TRAP, "PLAT_EVT_TRAP" },
	{ TOPO_SENSOR_STATE_ALERT_PLAT_SNMP_TRAP, "PLAT_SNMP_TRAP" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_presence_table[] = {
	{ TOPO_SENSOR_STATE_PRESENCE_PRESENT, "PRESENT" },
	{ TOPO_SENSOR_STATE_PRESENCE_ABSENT, "ABSENT" },
	{ TOPO_SENSOR_STATE_PRESENCE_DISABLED, "DISABLED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_lan_table[] = {
	{ TOPO_SENSOR_STATE_LAN_HEARTBEAT_LOST, "HEARTBEAT_LOST" },
	{ TOPO_SENSOR_STATE_LAN_HEARTBEAT, "HEARTBEAT" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_health_table[] = {
	{ TOPO_SENSOR_STATE_HEALTH_SENSOR_ACC_DEGRADED, "SENSOR_ACC_DEGRADED" },
	{ TOPO_SENSOR_STATE_HEALTH_CNTLR_ACC_DEGRADED, "CNTLR_ACC_DEGRADED" },
	{ TOPO_SENSOR_STATE_HEALTH_CNTLR_OFFLINE, "CNTLR_OFFLINE" },
	{ TOPO_SENSOR_STATE_HEALTH_CNTLR_UNAVAIL, "CNTLR_UNAVAIL" },
	{ TOPO_SENSOR_STATE_HEALTH_SENSOR_FAILURE, "SENSOR_FAILURE" },
	{ TOPO_SENSOR_STATE_HEALTH_FRU_FAILURE, "FRU_FAILURE" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_battery_table[] = {
	{ TOPO_SENSOR_STATE_BATTERY_LOW, "LOW" },
	{ TOPO_SENSOR_STATE_BATTERY_FAILED, "FAILED" },
	{ TOPO_SENSOR_STATE_BATTERY_PRESENCE, "PRESENCE" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_audit_table[] = {
	{ TOPO_SENSOR_STATE_AUDIT_SESSION_ACTIVATED, "SESSION_ACTIVATED" },
	{ TOPO_SENSOR_STATE_AUDIT_SESSION_DEACTIVATED, "SESSION_DEACTIVATED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_version_table[] = {
	{ TOPO_SENSOR_STATE_VERSION_HW_CHANGE, "HW_CHANGE" },
	{ TOPO_SENSOR_STATE_VERSION_SW_CHANGE, "SW_CHANGE" },
	{ TOPO_SENSOR_STATE_VERSION_HW_INCOMPATIBLE, "HW_INCOMPATIBLE" },
	{ TOPO_SENSOR_STATE_VERSION_SW_INCOMPATIBLE, "SW_INCOMPATIBLE" },
	{ TOPO_SENSOR_STATE_VERSION_HW_INVAL, "HW_INVAL" },
	{ TOPO_SENSOR_STATE_VERSION_SW_INVAL, "SW_INVAL" },
	{ TOPO_SENSOR_STATE_VERSION_HW_CHANGE_SUCCESS, "HW_CHANGE_SUCCESS" },
	{ TOPO_SENSOR_STATE_VERSION_SW_CHANGE_SUCCESS, "SW_CHANGE_SUCCESS" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_fru_state_table[] = {
	{ TOPO_SENSOR_STATE_FRU_STATE_NOT_INSTALLED, "NOT_INSTALLED" },
	{ TOPO_SENSOR_STATE_FRU_STATE_INACTIVE, "INACTIVE" },
	{ TOPO_SENSOR_STATE_FRU_STATE_ACT_REQ, "ACT_REQ" },
	{ TOPO_SENSOR_STATE_FRU_STATE_ACT_INPROGRESS, "ACT_INPROGRESS" },
	{ TOPO_SENSOR_STATE_FRU_STATE_ACTIVE, "ACTIVE" },
	{ TOPO_SENSOR_STATE_FRU_STATE_DEACT_REQ, "DEACT_REQ" },
	{ TOPO_SENSOR_STATE_FRU_STATE_DEACT_INPROGRESS, "DEACT_INPROGRESS" },
	{ TOPO_SENSOR_STATE_FRU_STATE_COMM_LOST, "COMM_LOST" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_thresh_table[] = {
	{ TOPO_SENSOR_STATE_THRESH_LOWER_NONCRIT, "LOWER_NONCRIT" },
	{ TOPO_SENSOR_STATE_THRESH_LOWER_CRIT, "LOWER_CRIT" },
	{ TOPO_SENSOR_STATE_THRESH_LOWER_NONREC, "LOWER_NONREC" },
	{ TOPO_SENSOR_STATE_THRESH_UPPER_NONCRIT, "UPPER_NONCRIT" },
	{ TOPO_SENSOR_STATE_THRESH_UPPER_CRIT, "UPPER_CRIT" },
	{ TOPO_SENSOR_STATE_THRESH_UPPER_NONREC, "UPPER_NONREC" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_usage_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_USAGE_IDLE, "IDLE" },
	{ TOPO_SENSOR_STATE_GENERIC_USAGE_ACTIVE, "ACTIVE" },
	{ TOPO_SENSOR_STATE_GENERIC_USAGE_BUSY, "BUSY" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_state_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_STATE_DEASSERTED, "DEASSERTED" },
	{ TOPO_SENSOR_STATE_GENERIC_STATE_ASSERTED, "ASSERTED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_predfail_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_PREDFAIL_DEASSERTED, "DEASSERTED" },
	{ TOPO_SENSOR_STATE_GENERIC_PREDFAIL_ASSERTED, "ASSERTED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_limit_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_LIMIT_NOT_EXCEEDED, "NOT_EXCEEDED" },
	{ TOPO_SENSOR_STATE_GENERIC_LIMIT_EXCEEDED, "EXCEEDED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_perf_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_PERFORMANCE_MET, "MET" },
	{ TOPO_SENSOR_STATE_GENERIC_PERFORMANCE_LAGS, "LAGS" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_severity_table[] = {
	{ TOPO_SENSOR_STATE_SEVERITY_OK, "OK" },
	{ TOPO_SENSOR_STATE_SEVERITY_NONCRIT_GOING_HIGH, "NONCRIT_GOING_HIGH" },
	{ TOPO_SENSOR_STATE_SEVERITY_CRIT_GOING_HIGH, "CRIT_GOING_HIGH" },
	{ TOPO_SENSOR_STATE_SEVERITY_NONREC_GOING_HIGH, "NONREC_GOING_HIGH" },
	{ TOPO_SENSOR_STATE_SEVERITY_NONCRIT_GOING_LOW, "NONCRIT_GOING_LOW" },
	{ TOPO_SENSOR_STATE_SEVERITY_CRIT_GOING_LOW, "CRIT_GOING_LOW" },
	{ TOPO_SENSOR_STATE_SEVERITY_NONREC_GOING_LOW, "NONREC_GOING_LOW" },
	{ TOPO_SENSOR_STATE_SEVERITY_MONITOR, "MONITOR" },
	{ TOPO_SENSOR_STATE_SEVERITY_INFORMATIONAL, "INFORMATIONAL" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_presence_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_PRESENCE_DEASSERTED, "DEASSERTED" },
	{ TOPO_SENSOR_STATE_GENERIC_PRESENCE_ASSERTED, "ASSERTED" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_avail_table[] = {
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_status_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_RUNNING, "RUNNING" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_IN_TEST, "IN_TEST" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_POWER_OFF, "POWER_OFF" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_ONLINE, "ONLINE" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_OFFLINE, "OFFLINE" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_OFF_DUTY, "OFF_DUTY" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_DEGRADED, "DEGRADED" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_POWER_SAVE, "POWER_SAVE" },
	{ TOPO_SENSOR_STATE_GENERIC_STATUS_INSTALL_ERR, "INSTALL_ERR" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_acpi_pwr_table[] = {
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_failure_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_FAIL_DEASSERTED, "DEASSERTED" },
	{ TOPO_SENSOR_STATE_GENERIC_FAIL_NONRECOV, "NONRECOV" },
	{ TOPO_SENSOR_STATE_GENERIC_FAIL_CRITICAL, "CRITICAL" },
	{ 0, NULL }
};

topo_name_trans_t topo_sensor_states_generic_ok_table[] = {
	{ TOPO_SENSOR_STATE_GENERIC_OK_DEASSERTED, "DEASSERTED" },
	{ TOPO_SENSOR_STATE_GENERIC_OK_ASSERTED, "ASSERTED" },
	{ 0, NULL }
};
